### ISSUE TITLE
Add Flight tracking functionality

### ISSUE THREAD

**Issue by mikedevita** [VAMSApp/OnAirDiscordBot#3]
add functionality to refresh Flights on an interval by doing:
- [x] define required models in `schema.prisma`
- [x]  define getVAFlights method in `OnAir.ts` to fetch VA Flight data from the OnAir Api
- [x] define new `FlightTranslator`  class in `translators/FlightTranslator.ts' to translate an OnAir flight into a Prisma/db Flight
- [x] define new `FlightProcessor` class in `processors/FlightProcessor.ts` to process each OnAir flight
- [ ]  define refreshVAFlights method in `OnAir.ts` to call `getVAFlights()` and use the new `FlightProcessor` class to update the Flights
  - use refreshVAFleets as a mock example for refreshVAFlights

next, add functionality to track when Flights depart, arrive, and send an Event. Details for this still TBD.

This depends on database persistence being implemented first #8

**Comment by kbieda** [comment]
+1 vote!
